### ISSUE TITLE
delete tar file?

### ISSUE THREAD

**Issue by FingerRec** [epic-kitchens/starter-kit-action-recognition#7]
after download frames and tar, why not remove .tar file? which will cost more disk space.

**Comment by willprice** [comment]
Because it's typically handy to keep the tars around for copying over to other machines since copying millions of small files takes much longer than one large file. 

Regardless, the user can still modify the snakemake file to remove the tar files if they so wish, but I'll keep this default behaviour as the download can take a significant amount of time for some people; if something goes wrong post-download and the workflow removes the tar files they'd have to redownload them which would be frustrating.
